FROM ubuntu:trusty

RUN apt-get update\
 && apt-get install -y --no-install-recommends\
     stone\
 && apt-get clean\
 &&  rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*

ENTRYPOINT ["stone"]

